### ISSUE TITLE
threadlocalmutex.com not rendering some text

### ISSUE THREAD

**Issue by marotc** [rawrunprotected/hilbert_curves#2]
I find the post on you site very interesting, especially http://threadlocalmutex.com/?p=126 and http://threadlocalmutex.com/?p=149. The tricks described seem to be extremely impressive.
However, some text is missing and there are plenty of warnings:

`Warning: preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /www/htdocs/w01305b2/threadlocalmutex.com/wp-content/plugins/latex/latex.php on line 47`

I really hope that you can fix this, because I'm not able to understand your code without the maths behind it.

As @dkourilov pointed out in #1 , this is the only way to contact you.

**Comment by rawrunprotected** [comment]
Sorry, should be fixed now.
